// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCoreExeName() {
  return window['go']['main']['App']['GetCoreExeName']();
}

export function GetSchema() {
  return window['go']['main']['App']['GetSchema']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsExist(arg1) {
  return window['go']['main']['App']['IsExist'](arg1);
}

export function LoadJSON(arg1) {
  return window['go']['main']['App']['LoadJSON'](arg1);
}

export function RunExecCore(arg1, arg2) {
  return window['go']['main']['App']['RunExecCore'](arg1, arg2);
}

export function RunExecCoreWithArgs(arg1) {
  return window['go']['main']['App']['RunExecCoreWithArgs'](arg1);
}

export function SaveJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveJSON'](arg1, arg2);
}

export function SelectExistConfigFile(arg1) {
  return window['go']['main']['App']['SelectExistConfigFile'](arg1);
}

export function SelectSaveConfigFile(arg1) {
  return window['go']['main']['App']['SelectSaveConfigFile'](arg1);
}
