// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<string>;

export function GetCoreExeName():Promise<string>;

export function GetSchema():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsExist(arg1:string):Promise<boolean>;

export function LoadJSON(arg1:string):Promise<string>;

export function RunExecCore(arg1:string,arg2:string):Promise<string>;

export function RunExecCoreWithArgs(arg1:Array<string>):Promise<string>;

export function SaveJSON(arg1:string,arg2:string):Promise<Error>;

export function SelectExistConfigFile(arg1:string):Promise<string>;

export function SelectSaveConfigFile(arg1:string):Promise<string>;
